import type { CatalogItem } from './types';

/**
 * Verified against monis.rent on 2026-09-27 (names, categories, surfaces, prices).
 * Prices are "From" variant minimums, USD per week.
 * Dual-Motor Electric Standing Desk excluded (out of stock at fetch time).
 * Footprints are design estimates in meters — calibrate against real model
 * dimensions during the Slice 8 asset pipeline.
 */
export const CATALOG: CatalogItem[] = [
  {
    sku: 'desk-electrical',
    name: 'Electrical Adjustable Desk',
    category: 'desk',
    surface: 'floor',
    weeklyPrice: 6,
    footprint: [1.6, 0.8],
    model: { kind: 'gltf', url: '/models/desk-electrical.glb' },
  },
  {
    sku: 'desk-mechanical',
    name: 'Mechanical Adjustable Desk',
    category: 'desk',
    surface: 'floor',
    weeklyPrice: 7,
    footprint: [1.6, 0.8],
    model: { kind: 'gltf', url: '/models/desk-mechanical.glb' },
  },
  {
    sku: 'chair-ergonomic',
    name: 'Ergonomic Office Chair (Fantech OCA259S)',
    category: 'chair',
    surface: 'floor',
    weeklyPrice: 6,
    footprint: [0.65, 0.65],
    model: { kind: 'gltf', url: '/models/chair-ergonomic.glb' },
  },
  {
    sku: 'monitor-1c',
    name: '24" Full HD Office Monitor 1C',
    category: 'monitor',
    surface: 'desk',
    weeklyPrice: 5,
    footprint: [0.55, 0.2],
    model: { kind: 'primitive', primitive: 'monitor' },
  },
  {
    sku: 'monitor-a24i',
    name: '24" Full HD Office Monitor A24i',
    category: 'monitor',
    surface: 'desk',
    weeklyPrice: 6,
    footprint: [0.55, 0.2],
    model: { kind: 'primitive', primitive: 'monitor' },
  },
  {
    sku: 'monitor-a24i-2026',
    name: '24" Full HD Office Monitor A24i 2026',
    category: 'monitor',
    surface: 'desk',
    weeklyPrice: 6.5,
    footprint: [0.55, 0.2],
    model: { kind: 'primitive', primitive: 'monitor' },
  },
  {
    sku: 'monitor-a27i',
    name: '27" Full HD Office Monitor A27i',
    category: 'monitor',
    surface: 'desk',
    weeklyPrice: 8,
    footprint: [0.62, 0.2],
    model: { kind: 'primitive', primitive: 'monitor' },
  },
  {
    sku: 'monitor-a27u-4k',
    name: '27" 4K Multimedia Monitor (Redmi A27U)',
    category: 'monitor',
    surface: 'desk',
    weeklyPrice: 12,
    footprint: [0.62, 0.2],
    model: { kind: 'primitive', primitive: 'monitor' },
  },
  {
    sku: 'monitor-lg-ergo-32',
    name: '32" QHD Ergonomic Monitor (LG Ergo)',
    category: 'monitor',
    surface: 'desk',
    weeklyPrice: 19,
    footprint: [0.75, 0.22],
    model: { kind: 'primitive', primitive: 'monitor' },
  },
  {
    sku: 'monitor-xiaomi-curved-34',
    name: '34" 4K Gaming Monitor (Xiaomi curved)',
    category: 'monitor',
    surface: 'desk',
    weeklyPrice: 19,
    footprint: [0.8, 0.25],
    model: { kind: 'primitive', primitive: 'monitor' },
  },
  {
    sku: 'lamp-desk-1s',
    name: 'Smart LED Desk Lamp 1S',
    category: 'lamp',
    surface: 'desk',
    weeklyPrice: 3,
    footprint: [0.15, 0.15],
    model: { kind: 'primitive', primitive: 'lamp' },
  },
  {
    sku: 'lamp-light-bar',
    name: 'Monitor Light Bar',
    category: 'lamp',
    surface: 'desk',
    weeklyPrice: 3,
    footprint: [0.45, 0.1],
    model: { kind: 'primitive', primitive: 'light-bar' },
  },
  {
    sku: 'lamp-hue-signe',
    name: 'Hue Signe Gradient Lamp',
    category: 'lamp',
    surface: 'floor',
    weeklyPrice: 9,
    footprint: [0.25, 0.25],
    model: { kind: 'primitive', primitive: 'lamp' },
  },
  {
    sku: 'accessory-mx-keyboard',
    name: 'Logitech MX Keyboard',
    category: 'accessory',
    surface: 'desk',
    weeklyPrice: 6,
    footprint: [0.44, 0.14],
    model: { kind: 'primitive', primitive: 'keyboard' },
  },
  {
    sku: 'accessory-mx-mouse-s3',
    name: 'Logitech MX Master Mouse S3',
    category: 'accessory',
    surface: 'desk',
    weeklyPrice: 3,
    footprint: [0.12, 0.08],
    model: { kind: 'primitive', primitive: 'mouse' },
  },
  {
    sku: 'accessory-webcam-4k',
    name: 'Logitech 4K Webcam',
    category: 'accessory',
    surface: 'desk',
    weeklyPrice: 6,
    footprint: [0.1, 0.1],
    model: { kind: 'primitive', primitive: 'webcam' },
  },
  {
    sku: 'accessory-nespresso-essenza',
    name: 'Nespresso Essenza Coffee Machine',
    category: 'accessory',
    surface: 'floor',
    weeklyPrice: 7,
    footprint: [0.2, 0.3],
    model: { kind: 'primitive', primitive: 'coffee-machine' },
  },
  {
    sku: 'accessory-bosch-coffee-maker',
    name: 'Bosch Coffee Maker',
    category: 'accessory',
    surface: 'floor',
    weeklyPrice: 3,
    footprint: [0.25, 0.3],
    model: { kind: 'primitive', primitive: 'coffee-machine' },
  },
  {
    sku: 'accessory-power-strip-3',
    name: 'Smart Power Strip 3',
    category: 'accessory',
    surface: 'floor',
    weeklyPrice: 1,
    footprint: [0.3, 0.1],
    model: { kind: 'primitive', primitive: 'power-strip' },
  },
  {
    sku: 'accessory-whiteboard',
    name: 'Magnetic Whiteboard',
    category: 'accessory',
    surface: 'floor',
    weeklyPrice: 4.5,
    footprint: [1.2, 0.05],
    model: { kind: 'primitive', primitive: 'whiteboard' },
  },
];

/** SKU → item lookup for codec hydration joins and pricing. */
export const CATALOG_BY_ID: ReadonlyMap<string, CatalogItem> = new Map(
  CATALOG.map((item) => [item.sku, item]),
);
